### ISSUE TITLE
Image fusion/deconvolution RunTimeException error

### ISSUE THREAD

**Issue by sundar07** [fiji/SPIM_Registration#119]
Hi
  I am trying to use the multiview reconstruction plugin to fuse and deconvolve the images taken using a custom light-sheet microscope. 
I am imaging zebrafish embryos in a PTFE tube. The imaging was performed from 6 angles and bead information (from below the embryo) was also collected from the same tube. Fusion was first performed on the bead images and duplicated on to the embryo images. I extracted PSF of beads using the image fusion/deconvolution algorithm and provided the PSF as an extra file while fusing embryo images. However, when I proceed with image fusion/deconvolution for the embryo images, I get the attached RunTimeException error. 

![deconv_trouble](https://cloud.githubusercontent.com/assets/10779214/24100477/51910ca4-0d6c-11e7-9ff3-75e97b074cb5.jpg)

Some details: FIJI is set to a memory of 75 GB (system memory is 95 GB). I updated java to the latest version and also downloaded latest fiji. All the images are stored in a server and I have prompted the program to save the fused/deconvolved files directly to the server as well.  

Any help will be wonderful.
Thanks a lot
Sundar

**Comment by Agggy** [comment]
Hi! Did you ever solve this issue? I think I have the same problem...

**Comment by sundar07** [comment]
Yes, this problem got solved for me by computing the deconvolution in blocks of size 256 by 256 by 256 instead of 512 by 512 by 512. Now, we have upgraded our system to 12 GB GPU and I can now do the deconvolution with higher block size. Hope this helps!

**Comment by StephanPreibisch** [comment]
Hi, thanks! I also highly recommend switching to BigStitcher that contains the new version of multiview-reconstruction. This software here is completely outdated by now.
