### ISSUE TITLE
Re-save HDF5 into a separate directory

### ISSUE THREAD

**Issue by stevenedwards** [fiji/SPIM_Registration#123]
When using LOCI bio formats to define a dataset (.czi in this case), is it possible to change the directory of the created .xml files? i.e. in a directory that doesn't contain the raw data

Similarly, when re-saving a dataset as HDF5, is it possible to change the save location to a directory that does not contain the raw data?

I believe this would be beneficial if (1) the raw data and HDF5 is too large to fit on an SSD, therefore allowing users to save the raw data on a mechanical disk drive and HDF5 on SSD for further processing. And (2) would allow users to convert to HDF5 over a network, leaving the raw data on the microscope acquisition computer and only saving the HDF5 on the workstation. 

Apologies if this is possible and I have overlooked something!

**Comment by schmiedc** [comment]
Hi :) 

I think you can use the "Batch Processing" after you defined the dataset. 
Plugins > Multiview Reconstruction > Batch Processing > Resave > As HDF5

Select the XML and then there will be an Export path. 

Cheers,
Christopher

**Comment by stevenedwards** [comment]
Works like a charm! Thanks a lot.

/Steve
