### ISSUE TITLE
Automatically find Bounding Box Memory Error

### ISSUE THREAD

**Issue by lacan** [fiji/SPIM_Registration#126]
When trying to use 'Automatically find Bounding Box through image filtering' on a 8GB .h5 resaved dataset, the system eats up all the RAM of the machine (64GB) and Fiji crashes
Moreover the data was set to be downsampled by a factor of 4

**Comment by StephanPreibisch** [comment]
Mmh, that does sound like a bug, we'll investigate, thanks a lot for reporting @lacan!

**Comment by StephanPreibisch** [comment]
Hi, should be fixed with this commit: https://github.com/fiji/SPIM_Registration/commit/0c2b69ed0eebde405aced3258a36b17d82298695

Still needs testing.
