### ISSUE TITLE
SlideBook .SLD files do not load

### ISSUE THREAD

**Issue by RichardMyers** [fiji/SPIM_Registration#129]
After updating to latest FIJI I get the following exception/stack trace; it all worked a few weeks ago when I last updated my local Fiji.  This is likely related to PR #118 and I'll need to investigate further.  Perhaps updates were made to the other readers that also need to be made to SlideBook6ImgLoader . 

SlideBook6Reader initializing C:\Users\Richard Myers\Documents\3i\images\diSPIM\fish-spinal-cord-sm.sld
mpicbg.spim.data.SpimDataInstantiationException: could not find XmlIoBasicImgLoader implementation for SlideBook6ImgLoader
	at mpicbg.spim.data.generic.sequence.ImgLoaders.createXmlIoForImgLoaderClass(ImgLoaders.java:93)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.toXml(XmlIoAbstractSequenceDescription.java:77)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.toXml(XmlIoAbstractSpimData.java:180)
	at spim.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:175)
	at spim.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:45)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.save(XmlIoAbstractSpimData.java:97)
	at spim.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:112)
	at spim.fiji.spimdata.SpimData2.saveXML(SpimData2.java:360)
	at spim.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:140)
	at spim.fiji.plugin.Data_Explorer.run(Data_Explorer.java:74)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RichardMyers** [comment]
Hi @StephanPreibisch @ctrueden , It looks like the 5.0.14 SPIM_Registration plugin does not load SLD files, but the 5.0.15 SNAPSHOT works.  Perhaps 5.0.14 [didn't deploy properly](https://travis-ci.org/fiji/SPIM_Registration/builds/252540294?utm_source=github_status&utm_medium=notification)? 

I don't see any other changes made to the plugin between the 5.0.14 release and creating the 5.0.15 Snapshot.

**Comment by RichardMyers** [comment]
I assume this is related to Fiji updating to [SciJava 16.1.0](https://github.com/fiji/fiji/commit/402d7ee30369c2e532f904685dc7c4c7cf2c517b) on May 24 and SPIM_Registration updating to [SciJava 16.2.0](https://github.com/fiji/SPIM_Registration/commit/3895eeba0c2a4eeefa02a1fae729dc37d7217e12) on July 11.

**Comment by StephanPreibisch** [comment]
Hi @RichardMyers, I'll make another release just to be sure it's not the reason ...

**Comment by StephanPreibisch** [comment]
Hi, I do not understand why, but the Travis build often, not always fails because it cannot find the sources. @ctrueden, do you have any idea what's the reason for that? I checked, the file does exist though.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project SPIM_Registration: Failed to deploy artifacts: Could not transfer artifact sc.fiji:SPIM_Registration:jar:sources:5.0.16 from/to imagej.releases (dav:http://maven.imagej.net/content/repositories/releases): Failed to transfer file: http://maven.imagej.net/content/repositories/releases/sc/fiji/SPIM_Registration/5.0.16/SPIM_Registration-5.0.16-sources.jar. Return code is: 400 -> [Help 1]

**Comment by StephanPreibisch** [comment]
After re-running the build from the travis website it now does not find the jar itself, I am really stuck here ...

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project SPIM_Registration: Failed to deploy artifacts: Could not transfer artifact sc.fiji:SPIM_Registration:jar:5.0.16 from/to imagej.releases (dav:http://maven.imagej.net/content/repositories/releases): Failed to transfer file: http://maven.imagej.net/content/repositories/releases/sc/fiji/SPIM_Registration/5.0.16/SPIM_Registration-5.0.16.jar. Return code is: 400 -> [Help 1]

**Comment by StephanPreibisch** [comment]
Well, I anyway put SPIM_Registration-5.0.16.jar into the Fiji uploader for now. @RichardMyers can you check if it works now again?

**Comment by StephanPreibisch** [comment]
Travis really only seems to work for Snapshots currently: https://github.com/fiji/SPIM_Registration/commits/master 
There is again no change except the pom-version itself ... I wonder what's behind that

**Comment by RichardMyers** [comment]
Thanks @StephanPreibisch! that fixed it.  Using latest SPIM_Registration-5.0.16.jar SLD files can again be read.

**Comment by ctrueden** [comment]
> Return code is: 400

This happens because you have a release version instead of a SNAPSHOT version. You can only deploy each release version to the repository once. In other words: releases are immutable. It is very important to "bump to next development cycle" after doing a release, changing e.g. `5.0.16` to `5.0.17-SNAPSHOT` in the next commit. Otherwise you will receive this error, and your Git history will be ambiguous in that you cannot tell by inspection of a commit is the _real_ `5.0.16` or not.

**Comment by StephanPreibisch** [comment]
Hi, thanks @ctrueden! But this only explains the follow up error, but it really happens for every release that I make, maybe it is best explained with this annotated screenshot:
![screen shot 2017-08-01 at 10 19 26](https://user-images.githubusercontent.com/1420587/28816033-a1aac072-76a3-11e7-9f3e-ccd5a8a14c0a.jpg)
The precise change was:
![screen shot 2017-08-01 at 10 19 47](https://user-images.githubusercontent.com/1420587/28816063-b817e920-76a3-11e7-9e0f-ce44eab3a1fd.png)

It feels like I do not understand something conceptually ... thanks so much for your help @ctrueden

**Comment by StephanPreibisch** [comment]
Another example is release version 5.0.13, exactly same thing, just the version in the pom.xml changed and it does not compile: https://github.com/fiji/SPIM_Registration/commit/2d1d9c4c4e9edd101936252ce6f43649b847afe9
![screen shot 2017-08-01 at 10 28 09](https://user-images.githubusercontent.com/1420587/28816181-26fa283a-76a4-11e7-8fd7-e3aee09b81e0.png)

**Comment by ctrueden** [comment]
Thanks for the clarification, @StephanPreibisch. I took a look earlier this week and it was not immediately obvious to me what the heck is going on. I'm planning to look again in more detail soon, but have a couple of urgent things on my plate to take care of first. I'll follow up again when I can.

**Comment by StephanPreibisch** [comment]
Thanks a lot @ctrueden! It is that urgent, things work despite of it. I just kind of want to understand if I do something wrong or if it is a hiccup of travis :)

**Comment by StephanPreibisch** [comment]
Sorry for forgetting the NOT :)
