### ISSUE TITLE
Unable to save multiview deconvolution as TIFF

### ISSUE THREAD

**Issue by Agggy** [fiji/SPIM_Registration#136]
So, I have been trying to work on some files in BigStitcher that I get from the Zeiss Z1 SPIM and everything seems to work until the multiview deconvolution step where fiji crushes if I ask it to save the file as TIFF. It works if save it as HDF5... 

Last time I tried, I got this error message:
![errors_console](https://user-images.githubusercontent.com/56698896/77140502-75cbdd00-6a3f-11ea-8e09-6fd24b16dcbf.png)
![workspace](https://user-images.githubusercontent.com/56698896/77140504-7795a080-6a3f-11ea-82ad-54fbc7a7128c.png)
![errors](https://user-images.githubusercontent.com/56698896/77140515-81b79f00-6a3f-11ea-856f-b7ba802f1e77.png)

I am a bit clueless here and hope that someone can give me some helpful tips so that I can finish my image analysis!

**Comment by ctrueden** [comment]
@Agggy Thanks for the report! Since this is an issue with BigStitcher, rather than the old grid/collection stitching plugins, I moved it to that issue tracker at PreibischLab/BigStitcher#67.

**Comment by StephanPreibisch** [comment]
Thanks @ctrueden
