### ISSUE TITLE
No detections that have been registered are available to extract a PSF, after starting off of a saved XML

### ISSUE THREAD

**Issue by emmenlau** [fiji/SPIM_Registration#83]
When I start from an original CZI, I can use Multiview Reconstruction all the way until the Fusion without problems. When later I closed Fiji and open it again on the same XML, then I can not perform the Fusion, due to an error "No detections that have been registered are available to extract a PSF". Why is that? I see interest points and registrations in the application, so I assume they are there?

**Comment by emmenlau** [comment]
Find the xml and interest points here: http://data.marssoft.de/zebrafish_beads0.5_4views.zip

**Comment by emmenlau** [comment]
When I remove the last transformation and re-register using interest points, the Fusion works. So it seems something is "forgotten" after saving and loading the XML. Strange that the application anyways shows 2 transformations on load?

**Comment by StephanPreibisch** [comment]
Hi @emmenlau,

there is a bug, I can see it, yes. All have a transformation but the corresponding interest points are not saved for all views (only for angleId=0, angle 142). Not sure how this happened. How did you compute the registrations so I can reproduce the error.

Thanks and all the best,
Stephan

**Comment by StephanPreibisch** [comment]
Ok, when I re-register your dataset using the beads from all views, it just works fine. It save thousands of correspondences that can then be used for extracting a PSF. Not sure how it goes wrong for you.

**Comment by emmenlau** [comment]
Yes its the same for me. When I load and re-register, it works. When I just load, it fails. Something must be different after re-registering?

**Comment by StephanPreibisch** [comment]
Well, how did you produce the version that you sent me if not like that?

**Comment by emmenlau** [comment]
Sorry I don't understand the question, now I'm confused :-) 

To clarify: In my eyes, the bug is: when I just load this XML (with its interest points and its registration), and try to start a Deconvolution Fusion, then the Fusion fails with the error "No detections that have been registered are available to extract a PSF". However when I load the same XML, delete the registration, run a new registration, and *then* try the Deconvolution Fusion, then the Fusion works. This seems like a bug to me, that the Fusion fails on the loaded XML, but works on the loaded XML after deleting and re-running the registration?!

**Comment by emmenlau** [comment]
I guess this can be closed now.
