### ISSUE TITLE
Is CUDA support only for windows at the moment ?

### ISSUE THREAD

**Issue by Xqua** [fiji/SPIM_Registration#88]
Hi, 

I run on Linux (Ubuntu 15.10) and I've been banging my head around to make CUDA work with the deconvolution. 
I've look everytwhere online, and except the mention that it support CUDA, there's not much information on how to make it work and which CUDA lib I should get and where to get it. 
I've grab some from places, but can get them to work for me. 

Any chance for a bit of support ?

Log:

```
Looking for native libraries ending with '.so', '.lib' in directory: '/home/USER/Software/Fiji.app/plugins/convolution3D/precompiled' ... 
Trying to load following library: /home/USER/Software/Fiji.app/plugins/convolution3D/precompiled/libConvolution3D_fftCUDAlib.so
Cannot load JNA library: java.lang.UnsatisfiedLinkError: Unable to load library '/home/USER/Software/Fiji.app/plugins/convolution3D/precompiled/libConvolution3D_fftCUDAlib.so': libcudart.so.5.0: cannot open shared object file: No such file or directory
Cannot load CUDA JNA library.
```

**Comment by psteinb** [comment]
Hi xqua-
From what I can tell, the environment you run in does not have the Cuda version installed that the library expects.
Please see to https://github.com/psteinb/FourierConvolutionCUDALib for building the Cuda library on your system. The build system supports Linux, OS X and Windows 7.
P

**Comment by Xqua** [comment]
Solved by compiling the CUDA FFT library ! Thanks !
