### ISSUE TITLE
spim.fiji.plugin.Data_Explorer did not find Java3D

### ISSUE THREAD

**Issue by RichardMyers** [fiji/SPIM_Registration#97]
We are using a fork of 2.4.5 and consistently getting this error:

![image](https://cloud.githubusercontent.com/assets/4415803/15712100/4a651588-2811-11e6-95b3-82171b1ef069.png)

The solution maybe to sync our fork, but I'm posting this in the hopes there is some faster way to get around this problem.  Despite getting this error from the SPIM_Registration plugin, Java3D works in Fiji.

I was able to fix the error by [installing Java3D](https://java3d.java.net/binary-builds.html) and copying the contents of Java3D/bin and Java3D/lib to my Fiji.app/java/win64/jdk1.8.0_66/jre/bin and lib directories.  As per a [related case](http://forum.imagej.net/t/java3d-issue-bonej-with-latest-fiji-version-problem-solved/1151) on the Fiji support forum.

**Comment by ctrueden** [comment]
Please see http://imagej.net/Java_3D for some details.

The gist is: you must choose whether to use the "old Java 3D" (Java 6 + Java 3D 1.5) or the "new Java 3D" (require Java 8 + Java 3D 1.6). Unfortunately, the old Java 3D 1.5 does not work with Java 8 across all platforms.

**Comment by ctrueden** [comment]
The master branch of this repository [switched to Java 3D 1.6 already](https://github.com/fiji/SPIM_Registration/commit/565b2d8c07ff0e1018cd51dd7a9edba2697c27d1).

**Comment by StephanPreibisch** [comment]
Thanks @ctrueden

**Comment by StephanPreibisch** [comment]
Hi @RichardMyers @ctrueden,

I made a new branch https://github.com/fiji/SPIM_Registration/tree/localVecmath to solve this issue for good. I do not need any dependency on the "real" Java3d, i.e. 3d visualisation & GPU stuff. I only need a few classes from vecmath and Transform3D that have no dependencies. I therefore locally duplicated them until the issues are sorted out. Still needs to be tested, but with that SPIM_Registration does not depend on Java3D anymore.

**Comment by ctrueden** [comment]
@StephanPreibisch OK, fair enough! As long as you don't need to reuse vecmath data objects between this library and others, that should be no problem.

**Comment by StephanPreibisch** [comment]
I know it is not beautiful at all. Once there is a better way (JDK independent fast vector math) we should use that solution.

**Comment by StephanPreibisch** [comment]
Or should I maybe rename the classes starting all with Tmp_ or so? What do you think @ctrueden?

**Comment by ctrueden** [comment]
I would not use a `tmp_` prefix. You can mark them as temporary in the javadoc if you want I guess. At some point in the future you will remove these classes in favor of the permanent thing, and then do a major version bump, yeah?

See also fiji/fiji#135.

**Comment by StephanPreibisch** [comment]
Thanks a lot @ctrueden, exactly that's the plan! I will merge it into master, I just tested it.

**Comment by StephanPreibisch** [comment]
It is merged @RichardMyers. You should have no problems with the current master anymore, independent of the JRE version you use.

**Comment by RichardMyers** [comment]
Thanks @ctrueden and @StephanPreibisch for the fast work figuring this out.  I'll sync and try it out.
